{
    'name': 'Accounting PDC Management',
    'summary': 'Allow use PDC',
    'author': 'Ever Business Solutions',
    'maintainer': 'Abdalla Mohamed',
    'website': 'https://www.everbsgroup.com/',
    'version': '15.0.1.2.2',
    'category': 'Accounting/Accounting',
    'license': 'OPL-1',
    'depends': ['account',
                #'promate_payment_custom_seq',
                # to appear custom sequence as display name.
                ],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'wizard/account_payment_register.xml',
        'wizard/account_payment_cash.xml',
        'wizard/account_payment_recheque.xml',
        'wizard/account_payment_pdc_writeoff.xml',
        'wizard/account_payment_pdc_collection_fees.xml',
        'wizard/account_hand_over_reject.xml',
        'wizard/account_payment_pdc_collect.xml',
        'wizard/account_payment_pdc_bounce.xml',
        'wizard/account_payment_pdc_payable_clear.xml',
        'views/account_journal.xml',
        'views/account_hand_over_pdc.xml',
        'views/account_payment.xml',
        'views/account_move.xml',
        'views/account_deposit_pdc.xml',
        'views/res_config_settings.xml',
        'data/ir_sequence.xml',
        'data/mail_template.xml',
        'data/ir_config_parameter.xml',
        'wizard/account_payment_pdc_payable_delivered.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
